---
name: CI/CD

on:
    release:
        types: [published]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.7

            - name: Upgrade pip
              run: |
                  pip install --upgrade pip
                  pip --version

            - name: Install Ansible
              run: |
                  pip install ansible

            - name: Trigger a new import on Galaxy.
              # First part of github.repository is the owner, second part is the repository name. We split for future reusability.
              run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_TOKEN }} --role-name $(echo ${{ github.repository }} | cut -d/ -f2 | tr '[:upper:]' '[:lower:]') $(echo ${{ github.repository }} | cut -d/ -f1 | tr '[:upper:]' '[:lower:]') $(echo ${{ github.repository }} | cut -d/ -f2 | tr '[:upper:]' '[:lower:]')
